/**
 * CREATE Script for init of DB
 */

-- Creates some product reviews

INSERT INTO REVIEWS (ID, AVERAGE_REVIEW_SCORE, NUMBER_OF_REVIEWS, PRODUCT_ID ) VALUES ( 1, 8,12223, 'M20324');

INSERT INTO REVIEWS (ID, AVERAGE_REVIEW_SCORE, NUMBER_OF_REVIEWS, PRODUCT_ID ) VALUES ( 2, 6.78, 2342, 'AC7836');

INSERT INTO REVIEWS (ID, AVERAGE_REVIEW_SCORE, NUMBER_OF_REVIEWS, PRODUCT_ID ) VALUES ( 3, 5.22, 2342, 'C77154');

INSERT INTO REVIEWS (ID, AVERAGE_REVIEW_SCORE, NUMBER_OF_REVIEWS, PRODUCT_ID ) VALUES ( 4, 9.22, 2342, 'BB5476');

-- Create s default user, that allow make writes operations

INSERT INTO USERS (ID, USERNAME, PASSWORD) VALUES ( 1, 'default', '$2a$04$I9Q2sDc4QGGg5WNTLmsz0.fvGv3OjoZyj81PrSFyGOqMphqfS2qKu');
